# Pagination Settings
paginate: 12
paginate_path: "/page:num/"

# Front Matter Defaults
defaults:
  - scope:
      path: ""          # all files in project
      type: "posts"     # specifically targets _posts folder
    values:
      layout: "single"
      author_profile: true
      read_time: true
      share: true
      related: true
      math: true
      comments: true
      # Sidebar & TOC Settings moved here to work globally:
      toc: true
      toc_label: "Research Highlights"
      toc_icon: "heart-pulse"
      toc_sticky: true

# Comment Settings
comments:
  provider: "giscus"
  giscus:
    repo_id: "R_kgDOSdr1qQ"
    category: "Senior Healtk" 
    category_id: "DIC_kwDOSdr1qc4C9Itp"
    mapping: "pathname"
    strict: "0"
    reactions_enabled: "1"
    input_position: "bottom"
    theme: "light"
    lang: "en"

# URL Structure
permalink: /posts/:title/
