name: build

on:
  push:
    branches:
      - master # If your branch is actually 'main', change this to 'main'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true 

    - name: Build Site
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production
