name: build

on:
  push:
    branches:
      - master # Double-check if your branch is 'master' or 'main'
  workflow_dispatch: {}
  repository_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true # This handles your Gemfile install and caching automatically

    - name: Build Site
      run: |
        bundle exec jekyll build
      env:
        JEKYLL_ENV: production
